name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: 'lint'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run Typescript checks (front-end)
        run: yarn test:ts:front
      - name: Run Typescript checks (back-end)
        run: yarn test:ts:back
      - name: Build the plugin
        run: yarn build
      - name: Verify plugin code
        run: yarn verify
  test:
    name: 'test'
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies plugin
        run: yarn --no-lockfile --unsafe-perm
      - name: Push the package to yalc
        run: yarn build
      - name: Add yalc package to the playground
        run: yarn playground:yalc-add
      - name: Install dependencies playground
        run: cd playground && yarn install --unsafe-perm
      - name: Build playground
        run: yarn playground:build
      - name: Run jest
        run: yarn test:jest
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn playground:start
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
